# Generated by Django 4.2 on 2023-09-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_post_mainphoto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="postname",
            new_name="title",
        ),
    ]
