# Generated by Django 4.2 on 2023-09-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_post_count_post_date_post_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="password",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
