# Generated by Django 4.2 on 2023-09-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_post_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
