# Generated by Django 4.2 on 2023-09-08 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_post_writer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date"]},
        ),
    ]
